# Generated by Django 3.1.1 on 2020-09-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GirlsLove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_name', models.CharField(max_length=50)),
                ('followee_name', models.CharField(max_length=50)),
            ],
        ),
    ]
