# Generated by Django 3.1.1 on 2020-10-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yagakimi_app', '0002_text_webrtc_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_relax',
            field=models.BooleanField(default=False),
        ),
    ]
